function Hd = elliptic
%ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 13-Jun-2022 11:39:14

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 96000;  % Sampling Frequency

N     = 4;      % Order
Fpass = 16000;  % Passband Frequency
Apass = 1;      % Passband Ripple (dB)
Astop = 60;     % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass('N,Fp,Ap,Ast', N, Fpass, Apass, Astop, Fs);
Hd = design(h, 'ellip');
set(Hd, 'Arithmetic', 'single');

% flatten coefficients for ARM
coeffs = reshape(Hd.sosMatrix(:,[1 2 3 5 6])' .* [1 1 1 -1 -1]',[],1);
% create string for copy/paste, cut off last ,\n
coeffStr = sprintf('%1.10ff,\n',coeffs);
disp(coeffStr(1:end-2));