#pragma once

#define MAX_VALUE_12BIT 4071
#define MIN_VALUE_12BIT 19

#define VECTORDEFAULTINITSIZE 20
#ifdef POLYRENDER
#define VOICESPERCHIP 4
#endif

#ifdef POLYCONTROL
#define VOICESPERCHIP 8
#endif
