#pragma once

#define CVTIMERINTERVALUS 250

#define SECONDSPERCVRENDER ((float)CVTIMERINTERVALUS / 1000000.0f)

#define NOTEIMPERFECTIONBUFFERSIZE 128
#define NOTEIMPERFECTIONWEIGHT 0.01f
#define LFOIMPERFECTIONWEIGHT 0.01f
#define ADSRIMPERFECTIONWEIGHT 0.01f